### ISSUE TITLE
Devhub import ssh key error

### ISSUE THREAD

**Issue by cadw** [devhub-tud/devhub#239] opened 2015-06-21 10:07 UTC
When I try to add a second SSH key, since my branches do not show up on Devhub and try to use Sourctree, I get the following error message, while the SSH key generated by sourcetree is fine.

Event: 8e30ba51-3ad5-488b-a304-c88ce799613a

**Comment by JWGmeligMeyling** [comment] 2015-06-21 10:09
Hi,

In order to fixed a previous bug we’ve added additional validation rules to the key setup process. These new validation rules don’t have informative error messages however. I suspect one of these validation rules is currently failing for your key. Could you please send me your public key so I can test it against our unit tests.

One thing you can try is to remove trailing newlines from the pasted data. Please let me know if this fixes your issue. Also keep in mind we only support ssh-rsa keys, but you already mentioned that you use RSA keys so that should be right.

Kind regards,

Jan-Willem
j.gmeligmeyling@student.tudelft.nl

Duplicate of #235

**Closed by JWGmeligMeyling** 2015-06-21 10:09 UTC
Labels: duplicate
